send_ir:
  description: Send the specified infrared code via MEIZU remoter
  fields:
    entity_id:
      description: Entity ID of MEIZU remoter entity
      example: "sensor.683e34c2df1c_remoter"
    ir_code:
      description: Infrared code for send
      example: "65001C63C68D8000C8"

bind:
  description: Put the gateway into bing mode, to bind a new remoter to gateway
  fields:
    serial_no:
      description: The serial number of gateway
      example: "1E329D"

bind_threshold:
  description: Set the binding mode RSSI threshold to find nearly device
  fields:
    serial_no:
      description: The serial number of gateway
      example: "1E329D"
    threshold:
      description: The RSSI threshold
      example: -35

remove_bind:
  description: Remove a remoter from Home Assistant and binded gateway
  fields:
    entity_id:
      description: Entity ID of MEIZU remoter entity
      example: "sensor.683e34c2df1c_remoter"